// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPJoBqMmy2kmSL1lqp5nnee_nACOpr8h4',
    appId: '1:795440992614:web:2c37255ecb8d0c174b78a7',
    messagingSenderId: '795440992614',
    projectId: 'u-s-departments-and-age-gnkn5k',
    authDomain: 'u-s-departments-and-age-gnkn5k.firebaseapp.com',
    storageBucket: 'u-s-departments-and-age-gnkn5k.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKkjujp86K09K2aOeSxnch3j2-W-WfKNU',
    appId: '1:795440992614:android:fce9430ec7d30d514b78a7',
    messagingSenderId: '795440992614',
    projectId: 'u-s-departments-and-age-gnkn5k',
    storageBucket: 'u-s-departments-and-age-gnkn5k.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf2Mc8Wc6itBUvHbEtvQ_ILfBcfqZCOJA',
    appId: '1:795440992614:ios:d67b38e7d56258aa4b78a7',
    messagingSenderId: '795440992614',
    projectId: 'u-s-departments-and-age-gnkn5k',
    storageBucket: 'u-s-departments-and-age-gnkn5k.appspot.com',
    iosBundleId: 'com.trendmobileapp.usgovdepandagen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGKGWI7xWd9TXNGCMfGI_eDZVV6RsGfKg',
    authDomain: 'govt-departments-agencies.firebaseapp.com',
    projectId: 'govt-departments-agencies',
    storageBucket: 'govt-departments-agencies.firebasestorage.app',
    messagingSenderId: '123456789012',
    appId: '1:123456789012:macos:abcdef123456',
    iosBundleId: 'com.example.govtDepartmentsAndAgencies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGKGWI7xWd9TXNGCMfGI_eDZVV6RsGfKg',
    authDomain: 'govt-departments-agencies.firebaseapp.com',
    projectId: 'govt-departments-agencies',
    storageBucket: 'govt-departments-agencies.firebasestorage.app',
    messagingSenderId: '123456789012',
    appId: '1:123456789012:windows:abcdef123456',
  );
}