// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV4rLBTCtFHeWaqdifk90pWHH0tzZRVtg',
    appId: '1:795440992614:web:118e481d9ecfb2994b78a7',
    messagingSenderId: '795440992614',
    projectId: 'u-s-departments-and-age-gnkn5k',
    authDomain: 'u-s-departments-and-age-gnkn5k.firebaseapp.com',
    storageBucket: 'u-s-departments-and-age-gnkn5k.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKkjujp86K09K2aOeSxnch3j2-W-WfKNU',
    appId: '1:795440992614:android:fce9430ec7d30d514b78a7',
    messagingSenderId: '795440992614',
    projectId: 'u-s-departments-and-age-gnkn5k',
    storageBucket: 'u-s-departments-and-age-gnkn5k.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf2Mc8Wc6itBUvHbEtvQ_ILfBcfqZCOJA',
    appId: '1:795440992614:ios:d67b38e7d56258aa4b78a7',
    messagingSenderId: '795440992614',
    projectId: 'u-s-departments-and-age-gnkn5k',
    storageBucket: 'u-s-departments-and-age-gnkn5k.appspot.com',
    iosBundleId: 'com.trendmobileapp.usgovdepandagen',
  );
}
